apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: api
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
  namespace: demo
spec:
  selector:
    app: simple-api
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
