apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-deployment.yaml
  - nginx-deployment.yaml

commonLabels:
  managed-by: argocd
  version: v1.0.0

images:
  - name: nginx
    newTag: "1.25-alpine"
